# SPDX-License-Identifier: AGPL-3.0-only
# Generated from Orca Tab.cpp; see NOTICE.md.
SOURCE_REVISION = 'f520e9221f220657f752d269ead37dd61e9cb0c3'
LAYOUT = {'filament': [('filament_type', 'Filament', 'Basic information'),
              ('filament_vendor', 'Filament', 'Basic information'),
              ('filament_soluble', 'Filament', 'Basic information'),
              ('filament_is_support', 'Filament', 'Basic information'),
              ('filament_change_length', 'Filament', 'Basic information'),
              ('required_nozzle_HRC', 'Filament', 'Basic information'),
              ('default_filament_colour', 'Filament', 'Basic information'),
              ('filament_diameter', 'Filament', 'Basic information'),
              ('filament_adhesiveness_category', 'Filament', 'Basic information'),
              ('filament_density', 'Filament', 'Basic information'),
              ('filament_shrink', 'Filament', 'Basic information'),
              ('filament_shrinkage_compensation_z', 'Filament', 'Basic information'),
              ('filament_cost', 'Filament', 'Basic information'),
              ('temperature_vitrification', 'Filament', 'Basic information'),
              ('idle_temperature', 'Filament', 'Basic information'),
              ('nozzle_temperature_range_low', 'Filament', 'Basic information'),
              ('nozzle_temperature_range_high', 'Filament', 'Basic information'),
              ('pellet_flow_coefficient', 'Filament', 'Flow ratio and Pressure Advance'),
              ('filament_flow_ratio', 'Filament', 'Flow ratio and Pressure Advance'),
              ('enable_pressure_advance', 'Filament', 'Flow ratio and Pressure Advance'),
              ('pressure_advance', 'Filament', 'Flow ratio and Pressure Advance'),
              ('adaptive_pressure_advance', 'Filament', 'Flow ratio and Pressure Advance'),
              ('adaptive_pressure_advance_overhangs', 'Filament', 'Flow ratio and Pressure Advance'),
              ('adaptive_pressure_advance_bridges', 'Filament', 'Flow ratio and Pressure Advance'),
              ('adaptive_pressure_advance_model', 'Filament', 'Flow ratio and Pressure Advance'),
              ('activate_chamber_temp_control', 'Filament', 'Print chamber temperature'),
              ('chamber_temperature', 'Filament', 'Print chamber temperature'),
              ('chamber_minimal_temperature', 'Filament', 'Print chamber temperature'),
              ('nozzle_temperature_initial_layer', 'Filament', 'Print temperature'),
              ('nozzle_temperature', 'Filament', 'Print temperature'),
              ('supertack_plate_temp_initial_layer', 'Filament', 'Bed temperature'),
              ('supertack_plate_temp', 'Filament', 'Bed temperature'),
              ('cool_plate_temp_initial_layer', 'Filament', 'Bed temperature'),
              ('cool_plate_temp', 'Filament', 'Bed temperature'),
              ('textured_cool_plate_temp_initial_layer', 'Filament', 'Bed temperature'),
              ('textured_cool_plate_temp', 'Filament', 'Bed temperature'),
              ('eng_plate_temp_initial_layer', 'Filament', 'Bed temperature'),
              ('eng_plate_temp', 'Filament', 'Bed temperature'),
              ('hot_plate_temp_initial_layer', 'Filament', 'Bed temperature'),
              ('hot_plate_temp', 'Filament', 'Bed temperature'),
              ('textured_plate_temp_initial_layer', 'Filament', 'Bed temperature'),
              ('textured_plate_temp', 'Filament', 'Bed temperature'),
              ('filament_adaptive_volumetric_speed', 'Filament', 'Volumetric speed limitation'),
              ('filament_max_volumetric_speed', 'Filament', 'Volumetric speed limitation'),
              ('close_fan_the_first_x_layers', 'Cooling', 'Cooling for specific layer'),
              ('initial_layer_fan_speed', 'Cooling', 'Cooling for specific layer'),
              ('full_fan_speed_layer', 'Cooling', 'Cooling for specific layer'),
              ('fan_min_speed', 'Cooling', 'Part cooling fan'),
              ('fan_cooling_layer_time', 'Cooling', 'Part cooling fan'),
              ('fan_max_speed', 'Cooling', 'Part cooling fan'),
              ('slow_down_layer_time', 'Cooling', 'Part cooling fan'),
              ('reduce_fan_stop_start_freq', 'Cooling', 'Part cooling fan'),
              ('slow_down_for_layer_cooling', 'Cooling', 'Part cooling fan'),
              ('dont_slow_down_outer_wall', 'Cooling', 'Part cooling fan'),
              ('slow_down_min_speed', 'Cooling', 'Part cooling fan'),
              ('enable_overhang_bridge_fan', 'Cooling', 'Part cooling fan'),
              ('overhang_fan_threshold', 'Cooling', 'Part cooling fan'),
              ('overhang_fan_speed', 'Cooling', 'Part cooling fan'),
              ('internal_bridge_fan_speed', 'Cooling', 'Part cooling fan'),
              ('support_material_interface_fan_speed', 'Cooling', 'Part cooling fan'),
              ('ironing_fan_speed', 'Cooling', 'Part cooling fan'),
              ('additional_cooling_fan_speed', 'Cooling', 'Auxiliary part cooling fan'),
              ('activate_air_filtration', 'Cooling', 'Exhaust fan'),
              ('activate_air_filtration_during_print', 'Cooling', 'Exhaust fan'),
              ('during_print_exhaust_fan_speed', 'Cooling', 'Exhaust fan'),
              ('activate_air_filtration_on_completion', 'Cooling', 'Exhaust fan'),
              ('complete_print_exhaust_fan_speed', 'Cooling', 'Exhaust fan'),
              ('filament_retraction_length', 'Setting Overrides', 'Retraction'),
              ('filament_z_hop', 'Setting Overrides', 'Retraction'),
              ('filament_z_hop_types', 'Setting Overrides', 'Retraction'),
              ('filament_retract_lift_above', 'Setting Overrides', 'Retraction'),
              ('filament_retract_lift_below', 'Setting Overrides', 'Retraction'),
              ('filament_retract_lift_enforce', 'Setting Overrides', 'Retraction'),
              ('filament_retraction_speed', 'Setting Overrides', 'Retraction'),
              ('filament_deretraction_speed', 'Setting Overrides', 'Retraction'),
              ('filament_retract_restart_extra', 'Setting Overrides', 'Retraction'),
              ('filament_retraction_minimum_travel', 'Setting Overrides', 'Retraction'),
              ('filament_retract_when_changing_layer', 'Setting Overrides', 'Retraction'),
              ('filament_wipe', 'Setting Overrides', 'Retraction'),
              ('filament_wipe_distance', 'Setting Overrides', 'Retraction'),
              ('filament_retract_before_wipe', 'Setting Overrides', 'Retraction'),
              ('filament_retract_after_wipe', 'Setting Overrides', 'Retraction'),
              ('filament_long_retractions_when_cut', 'Setting Overrides', 'Retraction'),
              ('filament_retraction_distances_when_cut', 'Setting Overrides', 'Retraction'),
              ('filament_retract_length_toolchange', 'Setting Overrides', 'Retraction when switching material'),
              ('filament_retract_restart_extra_toolchange', 'Setting Overrides', 'Retraction when switching material'),
              ('filament_ironing_flow', 'Setting Overrides', 'Ironing'),
              ('filament_ironing_spacing', 'Setting Overrides', 'Ironing'),
              ('filament_ironing_inset', 'Setting Overrides', 'Ironing'),
              ('filament_ironing_speed', 'Setting Overrides', 'Ironing'),
              ('filament_start_gcode', 'Advanced', 'Filament start G-code'),
              ('filament_change_extrusion_role_gcode', 'Advanced', 'Change extrusion role G-code'),
              ('filament_end_gcode', 'Advanced', 'Filament end G-code'),
              ('filament_plugin_config_overrides', 'Advanced', 'Plugin Configuration'),
              ('filament_minimal_purge_on_wipe_tower', 'Multimaterial', 'Wipe tower parameters'),
              ('filament_tower_interface_pre_extrusion_dist', 'Multimaterial', 'Wipe tower parameters'),
              ('filament_tower_interface_pre_extrusion_length', 'Multimaterial', 'Wipe tower parameters'),
              ('filament_tower_ironing_area', 'Multimaterial', 'Wipe tower parameters'),
              ('filament_tower_interface_purge_volume', 'Multimaterial', 'Wipe tower parameters'),
              ('filament_tower_interface_print_temp', 'Multimaterial', 'Wipe tower parameters'),
              ('long_retractions_when_ec', 'Multimaterial', 'Multi Filament'),
              ('retraction_distances_when_ec', 'Multimaterial', 'Multi Filament'),
              ('filament_loading_speed_start',
               'Multimaterial',
               'Tool change parameters with single extruder MM printers'),
              ('filament_loading_speed', 'Multimaterial', 'Tool change parameters with single extruder MM printers'),
              ('filament_unloading_speed_start',
               'Multimaterial',
               'Tool change parameters with single extruder MM printers'),
              ('filament_unloading_speed', 'Multimaterial', 'Tool change parameters with single extruder MM printers'),
              ('filament_toolchange_delay', 'Multimaterial', 'Tool change parameters with single extruder MM printers'),
              ('filament_cooling_moves', 'Multimaterial', 'Tool change parameters with single extruder MM printers'),
              ('filament_cooling_initial_speed',
               'Multimaterial',
               'Tool change parameters with single extruder MM printers'),
              ('filament_cooling_final_speed',
               'Multimaterial',
               'Tool change parameters with single extruder MM printers'),
              ('filament_stamping_loading_speed',
               'Multimaterial',
               'Tool change parameters with single extruder MM printers'),
              ('filament_stamping_distance',
               'Multimaterial',
               'Tool change parameters with single extruder MM printers'),
              ('filament_ramming_parameters',
               'Multimaterial',
               'Tool change parameters with single extruder MM printers'),
              ('filament_multitool_ramming', 'Multimaterial', 'Tool change parameters with multi extruder MM printers'),
              ('filament_multitool_ramming_volume',
               'Multimaterial',
               'Tool change parameters with multi extruder MM printers'),
              ('filament_multitool_ramming_flow',
               'Multimaterial',
               'Tool change parameters with multi extruder MM printers'),
              ('compatible_printers', 'Dependencies', 'Compatible printers'),
              ('compatible_printers_condition', 'Dependencies', 'Compatible printers'),
              ('compatible_prints', 'Dependencies', 'Compatible process profiles'),
              ('compatible_prints_condition', 'Dependencies', 'Compatible process profiles'),
              ('filament_notes', 'Notes', 'Notes')],
 'machine': [('printable_area', 'Basic information', 'Printable space'),
             ('parallel_printheads_count', 'Basic information', 'Printable space'),
             ('bed_exclude_area', 'Basic information', 'Printable space'),
             ('printable_height', 'Basic information', 'Printable space'),
             ('support_multi_bed_types', 'Basic information', 'Printable space'),
             ('best_object_pos', 'Basic information', 'Printable space'),
             ('z_offset', 'Basic information', 'Printable space'),
             ('preferred_orientation', 'Basic information', 'Printable space'),
             ('printer_structure', 'Basic information', 'Advanced'),
             ('gcode_flavor', 'Basic information', 'Advanced'),
             ('gcode_skip_config_block', 'Basic information', 'Advanced'),
             ('pellet_modded_printer', 'Basic information', 'Advanced'),
             ('bbl_use_printhost', 'Basic information', 'Advanced'),
             ('printer_agent', 'Basic information', 'Advanced'),
             ('use_3mf', 'Basic information', 'Advanced'),
             ('scan_first_layer', 'Basic information', 'Advanced'),
             ('enable_power_loss_recovery', 'Basic information', 'Advanced'),
             ('disable_m73', 'Basic information', 'Advanced'),
             ('thumbnails', 'Basic information', 'Advanced'),
             ('use_relative_e_distances', 'Basic information', 'Advanced'),
             ('use_firmware_retraction', 'Basic information', 'Advanced'),
             ('time_cost', 'Basic information', 'Advanced'),
             ('printer_plugin_config_overrides', 'Basic information', 'Plugin Configuration'),
             ('fan_speedup_time', 'Basic information', 'Cooling Fan'),
             ('fan_speedup_overhangs', 'Basic information', 'Cooling Fan'),
             ('fan_kickstart', 'Basic information', 'Cooling Fan'),
             ('part_cooling_fan_min_pwm', 'Basic information', 'Cooling Fan'),
             ('extruder_clearance_radius', 'Basic information', 'Extruder Clearance'),
             ('extruder_clearance_dist_to_rod', 'Basic information', 'Extruder Clearance'),
             ('extruder_clearance_height_to_rod', 'Basic information', 'Extruder Clearance'),
             ('extruder_clearance_height_to_lid', 'Basic information', 'Extruder Clearance'),
             ('bed_mesh_min', 'Basic information', 'Adaptive bed mesh'),
             ('bed_mesh_max', 'Basic information', 'Adaptive bed mesh'),
             ('bed_mesh_probe_distance', 'Basic information', 'Adaptive bed mesh'),
             ('adaptive_bed_mesh_margin', 'Basic information', 'Adaptive bed mesh'),
             ('nozzle_type', 'Basic information', 'Accessory'),
             ('nozzle_hrc', 'Basic information', 'Accessory'),
             ('auxiliary_fan', 'Basic information', 'Accessory'),
             ('fan_direction', 'Basic information', 'Accessory'),
             ('support_chamber_temp_control', 'Basic information', 'Accessory'),
             ('support_air_filtration', 'Basic information', 'Accessory'),
             ('cooling_filter_enabled', 'Basic information', 'Accessory'),
             ('file_start_gcode', 'Machine G-code', 'File header G-code'),
             ('machine_start_gcode', 'Machine G-code', 'Machine start G-code'),
             ('machine_end_gcode', 'Machine G-code', 'Machine end G-code'),
             ('printing_by_object_gcode', 'Machine G-code', 'Printing by object G-code'),
             ('before_layer_change_gcode', 'Machine G-code', 'Before layer change G-code'),
             ('layer_change_gcode', 'Machine G-code', 'Layer change G-code'),
             ('time_lapse_gcode', 'Machine G-code', 'Timelapse G-code'),
             ('wrapping_detection_gcode', 'Machine G-code', 'Clumping Detection G-code'),
             ('change_filament_gcode', 'Machine G-code', 'Change filament G-code'),
             ('change_extrusion_role_gcode', 'Machine G-code', 'Change extrusion role G-code'),
             ('machine_pause_gcode', 'Machine G-code', 'Pause G-code'),
             ('template_custom_gcode', 'Machine G-code', 'Template Custom G-code'),
             ('printer_notes', 'Notes', 'Notes')],
 'process': [('layer_height', 'Quality', 'Layer height'),
             ('initial_layer_print_height', 'Quality', 'Layer height'),
             ('enable_mixed_color_sublayer', 'Quality', 'Layer height'),
             ('line_width', 'Quality', 'Line width'),
             ('initial_layer_line_width', 'Quality', 'Line width'),
             ('outer_wall_line_width', 'Quality', 'Line width'),
             ('inner_wall_line_width', 'Quality', 'Line width'),
             ('top_surface_line_width', 'Quality', 'Line width'),
             ('sparse_infill_line_width', 'Quality', 'Line width'),
             ('internal_solid_infill_line_width', 'Quality', 'Line width'),
             ('support_line_width', 'Quality', 'Line width'),
             ('bridge_line_width', 'Quality', 'Line width'),
             ('seam_position', 'Quality', 'Seam'),
             ('staggered_inner_seams', 'Quality', 'Seam'),
             ('seam_gap', 'Quality', 'Seam'),
             ('seam_slope_type', 'Quality', 'Seam'),
             ('seam_slope_conditional', 'Quality', 'Seam'),
             ('scarf_angle_threshold', 'Quality', 'Seam'),
             ('scarf_overhang_threshold', 'Quality', 'Seam'),
             ('scarf_joint_speed', 'Quality', 'Seam'),
             ('seam_slope_start_height', 'Quality', 'Seam'),
             ('seam_slope_entire_loop', 'Quality', 'Seam'),
             ('seam_slope_min_length', 'Quality', 'Seam'),
             ('seam_slope_steps', 'Quality', 'Seam'),
             ('scarf_joint_flow_ratio', 'Quality', 'Seam'),
             ('seam_slope_inner_walls', 'Quality', 'Seam'),
             ('role_based_wipe_speed', 'Quality', 'Seam'),
             ('wipe_speed', 'Quality', 'Seam'),
             ('wipe_on_loops', 'Quality', 'Seam'),
             ('wipe_inward', 'Quality', 'Seam'),
             ('wipe_inward_distance', 'Quality', 'Seam'),
             ('wipe_before_external_loop', 'Quality', 'Seam'),
             ('slice_closing_radius', 'Quality', 'Precision'),
             ('resolution', 'Quality', 'Precision'),
             ('enable_arc_fitting', 'Quality', 'Precision'),
             ('xy_hole_compensation', 'Quality', 'Precision'),
             ('xy_contour_compensation', 'Quality', 'Precision'),
             ('elefant_foot_compensation', 'Quality', 'Precision'),
             ('elefant_foot_layers_density', 'Quality', 'Precision'),
             ('elefant_foot_compensation_layers', 'Quality', 'Precision'),
             ('precise_outer_wall', 'Quality', 'Precision'),
             ('precise_z_height', 'Quality', 'Precision'),
             ('hole_to_polyhole', 'Quality', 'Precision'),
             ('hole_to_polyhole_threshold', 'Quality', 'Precision'),
             ('hole_to_polyhole_twisted', 'Quality', 'Precision'),
             ('hole_to_polyhole_max_edges', 'Quality', 'Precision'),
             ('ironing_type', 'Quality', 'Ironing'),
             ('ironing_pattern', 'Quality', 'Ironing'),
             ('ironing_flow', 'Quality', 'Ironing'),
             ('ironing_spacing', 'Quality', 'Ironing'),
             ('ironing_inset', 'Quality', 'Ironing'),
             ('ironing_angle', 'Quality', 'Ironing'),
             ('ironing_angle_fixed', 'Quality', 'Ironing'),
             ('zaa_enabled', 'Quality', 'Z contouring'),
             ('zaa_minimize_perimeter_height', 'Quality', 'Z contouring'),
             ('zaa_min_z', 'Quality', 'Z contouring'),
             ('zaa_dont_alternate_fill_direction', 'Quality', 'Z contouring'),
             ('wall_generator', 'Quality', 'Wall generator'),
             ('wall_transition_angle', 'Quality', 'Wall generator'),
             ('wall_transition_filter_deviation', 'Quality', 'Wall generator'),
             ('wall_transition_length', 'Quality', 'Wall generator'),
             ('wall_distribution_count', 'Quality', 'Wall generator'),
             ('initial_layer_min_bead_width', 'Quality', 'Wall generator'),
             ('min_bead_width', 'Quality', 'Wall generator'),
             ('min_feature_size', 'Quality', 'Wall generator'),
             ('min_length_factor', 'Quality', 'Wall generator'),
             ('wall_maximum_resolution', 'Quality', 'Wall generator'),
             ('wall_maximum_deviation', 'Quality', 'Wall generator'),
             ('wall_sequence', 'Quality', 'Walls and surfaces'),
             ('is_infill_first', 'Quality', 'Walls and surfaces'),
             ('wall_direction', 'Quality', 'Walls and surfaces'),
             ('print_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('top_solid_infill_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('bottom_solid_infill_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('set_other_flow_ratios', 'Quality', 'Walls and surfaces'),
             ('first_layer_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('outer_wall_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('inner_wall_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('overhang_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('sparse_infill_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('internal_solid_infill_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('gap_fill_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('support_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('support_interface_flow_ratio', 'Quality', 'Walls and surfaces'),
             ('only_one_wall_first_layer', 'Quality', 'Walls and surfaces'),
             ('only_one_wall_top', 'Quality', 'Walls and surfaces'),
             ('min_width_top_surface', 'Quality', 'Walls and surfaces'),
             ('reduce_crossing_wall', 'Quality', 'Walls and surfaces'),
             ('max_travel_detour_distance', 'Quality', 'Walls and surfaces'),
             ('small_area_infill_flow_compensation', 'Quality', 'Walls and surfaces'),
             ('small_area_infill_flow_compensation_model', 'Quality', 'Walls and surfaces'),
             ('bridge_flow', 'Quality', 'Bridging'),
             ('internal_bridge_flow', 'Quality', 'Bridging'),
             ('bridge_density', 'Quality', 'Bridging'),
             ('internal_bridge_density', 'Quality', 'Bridging'),
             ('thick_bridges', 'Quality', 'Bridging'),
             ('thick_internal_bridges', 'Quality', 'Bridging'),
             ('enable_extra_bridge_layer', 'Quality', 'Bridging'),
             ('dont_filter_internal_bridges', 'Quality', 'Bridging'),
             ('counterbore_hole_bridging', 'Quality', 'Bridging'),
             ('detect_overhang_wall', 'Quality', 'Overhangs'),
             ('unsupported_wall_last', 'Quality', 'Overhangs'),
             ('make_overhang_printable', 'Quality', 'Overhangs'),
             ('make_overhang_printable_angle', 'Quality', 'Overhangs'),
             ('make_overhang_printable_hole_size', 'Quality', 'Overhangs'),
             ('extra_perimeters_on_overhangs', 'Quality', 'Overhangs'),
             ('overhang_reverse', 'Quality', 'Overhangs'),
             ('overhang_reverse_internal_only', 'Quality', 'Overhangs'),
             ('overhang_reverse_threshold', 'Quality', 'Overhangs'),
             ('wall_loops', 'Strength', 'Walls'),
             ('alternate_extra_wall', 'Strength', 'Walls'),
             ('detect_thin_wall', 'Strength', 'Walls'),
             ('top_shell_layers', 'Strength', 'Top/bottom shells'),
             ('top_shell_thickness', 'Strength', 'Top/bottom shells'),
             ('top_surface_density', 'Strength', 'Top/bottom shells'),
             ('top_surface_pattern', 'Strength', 'Top/bottom shells'),
             ('top_surface_fill_order', 'Strength', 'Top/bottom shells'),
             ('top_layer_direction', 'Strength', 'Top/bottom shells'),
             ('top_surface_expansion', 'Strength', 'Top/bottom shells'),
             ('top_surface_expansion_margin', 'Strength', 'Top/bottom shells'),
             ('top_surface_expansion_direction', 'Strength', 'Top/bottom shells'),
             ('bottom_shell_layers', 'Strength', 'Top/bottom shells'),
             ('bottom_shell_thickness', 'Strength', 'Top/bottom shells'),
             ('bottom_surface_density', 'Strength', 'Top/bottom shells'),
             ('bottom_surface_pattern', 'Strength', 'Top/bottom shells'),
             ('bottom_surface_fill_order', 'Strength', 'Top/bottom shells'),
             ('bottom_layer_direction', 'Strength', 'Top/bottom shells'),
             ('center_of_surface_pattern', 'Strength', 'Top/bottom shells'),
             ('top_bottom_infill_wall_overlap', 'Strength', 'Top/bottom shells'),
             ('sparse_infill_density', 'Strength', 'Infill'),
             ('fill_multiline', 'Strength', 'Infill'),
             ('sparse_infill_pattern', 'Strength', 'Infill'),
             ('gyroid_optimized', 'Strength', 'Infill'),
             ('sparse_infill_smooth_factor', 'Strength', 'Infill'),
             ('infill_direction', 'Strength', 'Infill'),
             ('sparse_infill_rotate_template', 'Strength', 'Infill'),
             ('skin_infill_density', 'Strength', 'Infill'),
             ('skeleton_infill_density', 'Strength', 'Infill'),
             ('infill_lock_depth', 'Strength', 'Infill'),
             ('skin_infill_depth', 'Strength', 'Infill'),
             ('skin_infill_line_width', 'Strength', 'Infill'),
             ('skeleton_infill_line_width', 'Strength', 'Infill'),
             ('symmetric_infill_y_axis', 'Strength', 'Infill'),
             ('infill_shift_step', 'Strength', 'Infill'),
             ('lateral_lattice_angle_1', 'Strength', 'Infill'),
             ('lateral_lattice_angle_2', 'Strength', 'Infill'),
             ('infill_overhang_angle', 'Strength', 'Infill'),
             ('lightning_overhang_angle', 'Strength', 'Infill'),
             ('lightning_prune_angle', 'Strength', 'Infill'),
             ('lightning_straightening_angle', 'Strength', 'Infill'),
             ('infill_anchor_max', 'Strength', 'Infill'),
             ('infill_anchor', 'Strength', 'Infill'),
             ('internal_solid_infill_pattern', 'Strength', 'Infill'),
             ('solid_infill_direction', 'Strength', 'Infill'),
             ('solid_infill_rotate_template', 'Strength', 'Infill'),
             ('gap_fill_target', 'Strength', 'Infill'),
             ('filter_out_gap_fill', 'Strength', 'Infill'),
             ('separated_infills', 'Strength', 'Infill'),
             ('infill_wall_overlap', 'Strength', 'Infill'),
             ('align_infill_direction_to_model', 'Strength', 'Advanced'),
             ('extra_solid_infills', 'Strength', 'Advanced'),
             ('bridge_angle', 'Strength', 'Advanced'),
             ('internal_bridge_angle', 'Strength', 'Advanced'),
             ('relative_bridge_angle', 'Strength', 'Advanced'),
             ('minimum_sparse_infill_area', 'Strength', 'Advanced'),
             ('infill_combination', 'Strength', 'Advanced'),
             ('infill_combination_max_layer_height', 'Strength', 'Advanced'),
             ('detect_narrow_internal_solid_infill', 'Strength', 'Advanced'),
             ('ensure_vertical_shell_thickness', 'Strength', 'Advanced'),
             ('initial_layer_speed', 'Speed', 'First layer speed'),
             ('initial_layer_infill_speed', 'Speed', 'First layer speed'),
             ('initial_layer_travel_speed', 'Speed', 'First layer speed'),
             ('slow_down_layers', 'Speed', 'First layer speed'),
             ('outer_wall_speed', 'Speed', 'Other layers speed'),
             ('inner_wall_speed', 'Speed', 'Other layers speed'),
             ('small_perimeter_speed', 'Speed', 'Other layers speed'),
             ('small_perimeter_threshold', 'Speed', 'Other layers speed'),
             ('sparse_infill_speed', 'Speed', 'Other layers speed'),
             ('internal_solid_infill_speed', 'Speed', 'Other layers speed'),
             ('top_surface_speed', 'Speed', 'Other layers speed'),
             ('gap_infill_speed', 'Speed', 'Other layers speed'),
             ('ironing_speed', 'Speed', 'Other layers speed'),
             ('support_speed', 'Speed', 'Other layers speed'),
             ('support_interface_speed', 'Speed', 'Other layers speed'),
             ('small_support_perimeter_speed', 'Speed', 'Other layers speed'),
             ('small_support_perimeter_threshold', 'Speed', 'Other layers speed'),
             ('enable_overhang_speed', 'Speed', 'Overhang speed'),
             ('slowdown_for_curled_perimeters', 'Speed', 'Overhang speed'),
             ('overhang_1_4_speed', 'Speed', 'Overhang speed'),
             ('overhang_2_4_speed', 'Speed', 'Overhang speed'),
             ('overhang_3_4_speed', 'Speed', 'Overhang speed'),
             ('overhang_4_4_speed', 'Speed', 'Overhang speed'),
             ('bridge_speed', 'Speed', 'Overhang speed'),
             ('internal_bridge_speed', 'Speed', 'Overhang speed'),
             ('travel_speed', 'Speed', 'Travel speed'),
             ('default_acceleration', 'Speed', 'Acceleration'),
             ('outer_wall_acceleration', 'Speed', 'Acceleration'),
             ('inner_wall_acceleration', 'Speed', 'Acceleration'),
             ('bridge_acceleration', 'Speed', 'Acceleration'),
             ('sparse_infill_acceleration', 'Speed', 'Acceleration'),
             ('internal_solid_infill_acceleration', 'Speed', 'Acceleration'),
             ('initial_layer_acceleration', 'Speed', 'Acceleration'),
             ('initial_layer_travel_acceleration', 'Speed', 'Acceleration'),
             ('top_surface_acceleration', 'Speed', 'Acceleration'),
             ('travel_acceleration', 'Speed', 'Acceleration'),
             ('accel_to_decel_enable', 'Speed', 'Acceleration'),
             ('accel_to_decel_factor', 'Speed', 'Acceleration'),
             ('default_junction_deviation', 'Speed', 'Junction Deviation'),
             ('default_jerk', 'Speed', 'Jerk(XY)'),
             ('outer_wall_jerk', 'Speed', 'Jerk(XY)'),
             ('inner_wall_jerk', 'Speed', 'Jerk(XY)'),
             ('infill_jerk', 'Speed', 'Jerk(XY)'),
             ('top_surface_jerk', 'Speed', 'Jerk(XY)'),
             ('initial_layer_jerk', 'Speed', 'Jerk(XY)'),
             ('initial_layer_travel_jerk', 'Speed', 'Jerk(XY)'),
             ('travel_jerk', 'Speed', 'Jerk(XY)'),
             ('max_volumetric_extrusion_rate_slope', 'Speed', 'Advanced'),
             ('max_volumetric_extrusion_rate_slope_segment_length', 'Speed', 'Advanced'),
             ('extrusion_rate_smoothing_external_perimeter_only', 'Speed', 'Advanced'),
             ('enable_support', 'Support', 'Support'),
             ('support_type', 'Support', 'Support'),
             ('support_style', 'Support', 'Support'),
             ('support_threshold_angle', 'Support', 'Support'),
             ('support_threshold_overlap', 'Support', 'Support'),
             ('raft_first_layer_density', 'Support', 'Support'),
             ('raft_first_layer_expansion', 'Support', 'Support'),
             ('support_on_build_plate_only', 'Support', 'Support'),
             ('support_critical_regions_only', 'Support', 'Support'),
             ('support_remove_small_overhang', 'Support', 'Support'),
             ('raft_layers', 'Support', 'Raft'),
             ('raft_contact_distance', 'Support', 'Raft'),
             ('support_filament', 'Support', 'Filament for Supports'),
             ('support_interface_filament', 'Support', 'Filament for Supports'),
             ('support_interface_not_for_body', 'Support', 'Filament for Supports'),
             ('support_ironing', 'Support', 'Support ironing'),
             ('support_ironing_pattern', 'Support', 'Support ironing'),
             ('support_ironing_flow', 'Support', 'Support ironing'),
             ('support_ironing_spacing', 'Support', 'Support ironing'),
             ('support_top_z_distance', 'Support', 'Advanced'),
             ('support_bottom_z_distance', 'Support', 'Advanced'),
             ('tree_support_wall_count', 'Support', 'Advanced'),
             ('support_base_pattern', 'Support', 'Advanced'),
             ('support_base_pattern_spacing', 'Support', 'Advanced'),
             ('support_angle', 'Support', 'Advanced'),
             ('support_interface_top_layers', 'Support', 'Advanced'),
             ('support_interface_bottom_layers', 'Support', 'Advanced'),
             ('support_interface_pattern', 'Support', 'Advanced'),
             ('support_interface_spacing', 'Support', 'Advanced'),
             ('support_bottom_interface_spacing', 'Support', 'Advanced'),
             ('support_expansion', 'Support', 'Advanced'),
             ('support_object_xy_distance', 'Support', 'Advanced'),
             ('support_object_first_layer_gap', 'Support', 'Advanced'),
             ('bridge_no_support', 'Support', 'Advanced'),
             ('max_bridge_length', 'Support', 'Advanced'),
             ('independent_support_layer_height', 'Support', 'Advanced'),
             ('tree_support_tip_diameter', 'Support', 'Tree supports'),
             ('tree_support_branch_distance', 'Support', 'Tree supports'),
             ('tree_support_branch_distance_organic', 'Support', 'Tree supports'),
             ('tree_support_top_rate', 'Support', 'Tree supports'),
             ('tree_support_branch_diameter', 'Support', 'Tree supports'),
             ('tree_support_branch_diameter_organic', 'Support', 'Tree supports'),
             ('tree_support_branch_diameter_angle', 'Support', 'Tree supports'),
             ('tree_support_branch_angle', 'Support', 'Tree supports'),
             ('tree_support_branch_angle_organic', 'Support', 'Tree supports'),
             ('tree_support_angle_slow', 'Support', 'Tree supports'),
             ('tree_support_auto_brim', 'Support', 'Tree supports'),
             ('tree_support_brim_width', 'Support', 'Tree supports'),
             ('enable_prime_tower', 'Multimaterial', 'Prime tower'),
             ('prime_tower_skip_points', 'Multimaterial', 'Prime tower'),
             ('enable_tower_interface_features', 'Multimaterial', 'Prime tower'),
             ('enable_tower_interface_cooldown_during_tower', 'Multimaterial', 'Prime tower'),
             ('prime_tower_enable_framework', 'Multimaterial', 'Prime tower'),
             ('prime_tower_width', 'Multimaterial', 'Prime tower'),
             ('prime_volume', 'Multimaterial', 'Prime tower'),
             ('prime_tower_brim_width', 'Multimaterial', 'Prime tower'),
             ('prime_tower_infill_gap', 'Multimaterial', 'Prime tower'),
             ('wipe_tower_rotation_angle', 'Multimaterial', 'Prime tower'),
             ('wipe_tower_bridging', 'Multimaterial', 'Prime tower'),
             ('wipe_tower_extra_spacing', 'Multimaterial', 'Prime tower'),
             ('wipe_tower_extra_flow', 'Multimaterial', 'Prime tower'),
             ('wipe_tower_max_purge_speed', 'Multimaterial', 'Prime tower'),
             ('wipe_tower_wall_type', 'Multimaterial', 'Prime tower'),
             ('wipe_tower_cone_angle', 'Multimaterial', 'Prime tower'),
             ('wipe_tower_extra_rib_length', 'Multimaterial', 'Prime tower'),
             ('wipe_tower_rib_width', 'Multimaterial', 'Prime tower'),
             ('wipe_tower_fillet_wall', 'Multimaterial', 'Prime tower'),
             ('wipe_tower_no_sparse_layers', 'Multimaterial', 'Prime tower'),
             ('single_extruder_multi_material_priming', 'Multimaterial', 'Prime tower'),
             ('outer_wall_filament_id', 'Multimaterial', 'Filament for Features'),
             ('inner_wall_filament_id', 'Multimaterial', 'Filament for Features'),
             ('sparse_infill_filament_id', 'Multimaterial', 'Filament for Features'),
             ('internal_solid_filament_id', 'Multimaterial', 'Filament for Features'),
             ('top_surface_filament_id', 'Multimaterial', 'Filament for Features'),
             ('bottom_surface_filament_id', 'Multimaterial', 'Filament for Features'),
             ('wipe_tower_filament', 'Multimaterial', 'Filament for Features'),
             ('ooze_prevention', 'Multimaterial', 'Ooze prevention'),
             ('standby_temperature_delta', 'Multimaterial', 'Ooze prevention'),
             ('preheat_time', 'Multimaterial', 'Ooze prevention'),
             ('preheat_steps', 'Multimaterial', 'Ooze prevention'),
             ('flush_into_infill', 'Multimaterial', 'Flush options'),
             ('flush_into_objects', 'Multimaterial', 'Flush options'),
             ('flush_into_support', 'Multimaterial', 'Flush options'),
             ('interlocking_beam', 'Multimaterial', 'Advanced'),
             ('toolchange_ordering', 'Multimaterial', 'Advanced'),
             ('toolchange_cyclic_order', 'Multimaterial', 'Advanced'),
             ('toolchange_cyclic_first_layer', 'Multimaterial', 'Advanced'),
             ('interface_shells', 'Multimaterial', 'Advanced'),
             ('mmu_segmented_region_max_width', 'Multimaterial', 'Advanced'),
             ('mmu_segmented_region_interlocking_depth', 'Multimaterial', 'Advanced'),
             ('interlocking_beam_width', 'Multimaterial', 'Advanced'),
             ('interlocking_orientation', 'Multimaterial', 'Advanced'),
             ('interlocking_beam_layer_count', 'Multimaterial', 'Advanced'),
             ('interlocking_depth', 'Multimaterial', 'Advanced'),
             ('interlocking_boundary_avoidance', 'Multimaterial', 'Advanced'),
             ('skirt_loops', 'Others', 'Skirt'),
             ('skirt_type', 'Others', 'Skirt'),
             ('min_skirt_length', 'Others', 'Skirt'),
             ('skirt_distance', 'Others', 'Skirt'),
             ('skirt_start_angle', 'Others', 'Skirt'),
             ('skirt_speed', 'Others', 'Skirt'),
             ('skirt_height', 'Others', 'Skirt'),
             ('draft_shield', 'Others', 'Skirt'),
             ('single_loop_draft_shield', 'Others', 'Skirt'),
             ('brim_type', 'Others', 'Brim'),
             ('brim_width', 'Others', 'Brim'),
             ('brim_object_gap', 'Others', 'Brim'),
             ('brim_flow_ratio', 'Others', 'Brim'),
             ('brim_use_efc_outline', 'Others', 'Brim'),
             ('combine_brims', 'Others', 'Brim'),
             ('brim_ears_max_angle', 'Others', 'Brim'),
             ('brim_ears_detection_length', 'Others', 'Brim'),
             ('brim_ears_outer_only', 'Others', 'Brim'),
             ('slicing_mode', 'Others', 'Special mode'),
             ('print_sequence', 'Others', 'Special mode'),
             ('print_order', 'Others', 'Special mode'),
             ('spiral_mode', 'Others', 'Special mode'),
             ('spiral_mode_smooth', 'Others', 'Special mode'),
             ('spiral_mode_max_xy_smoothing', 'Others', 'Special mode'),
             ('spiral_starting_flow_ratio', 'Others', 'Special mode'),
             ('spiral_finishing_flow_ratio', 'Others', 'Special mode'),
             ('timelapse_type', 'Others', 'Special mode'),
             ('enable_wrapping_detection', 'Others', 'Special mode'),
             ('fuzzy_skin', 'Others', 'Fuzzy skin'),
             ('fuzzy_skin_mode', 'Others', 'Fuzzy skin'),
             ('fuzzy_skin_noise_type', 'Others', 'Fuzzy skin'),
             ('fuzzy_skin_point_distance', 'Others', 'Fuzzy skin'),
             ('fuzzy_skin_thickness', 'Others', 'Fuzzy skin'),
             ('fuzzy_skin_scale', 'Others', 'Fuzzy skin'),
             ('fuzzy_skin_octaves', 'Others', 'Fuzzy skin'),
             ('fuzzy_skin_persistence', 'Others', 'Fuzzy skin'),
             ('fuzzy_skin_ripples_per_layer', 'Others', 'Fuzzy skin'),
             ('fuzzy_skin_ripple_offset', 'Others', 'Fuzzy skin'),
             ('fuzzy_skin_layers_between_ripple_offset', 'Others', 'Fuzzy skin'),
             ('fuzzy_skin_first_layer', 'Others', 'Fuzzy skin'),
             ('reduce_infill_retraction', 'Others', 'G-code output'),
             ('gcode_add_line_number', 'Others', 'G-code output'),
             ('gcode_comments', 'Others', 'G-code output'),
             ('gcode_label_objects', 'Others', 'G-code output'),
             ('exclude_object', 'Others', 'G-code output'),
             ('filename_format', 'Others', 'G-code output'),
             ('process_change_extrusion_role_gcode', 'Others', 'Change extrusion role G-code'),
             ('post_process', 'Others', 'Post-processing Scripts'),
             ('slicing_pipeline_plugin', 'Others', 'Slicing Pipeline Plugin'),
             ('print_plugin_config_overrides', 'Others', 'Plugin Configuration'),
             ('notes', 'Others', 'Notes')]}
